name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: dotnet-sonarscanner
      uses: Secbyte/dotnet-sonarscanner@2.1
      with:
        buildCommand: dotnet build .
        testCommand: dotnet test .
        projectKey: Cyber-Pet_Api
        projectName: Cyber-Pet_Api
        sonarOrganisation: cyber-pet
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Test
      run: dotnet test
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
